states = State.create([
  { :name => 'Alabama', :abbreviation => 'AL', :ansi_code => '1', :statens => '1779775'},
  { :name => 'Alaska', :abbreviation => 'AK', :ansi_code => '2', :statens => '1785533'},
  { :name => 'Arizona', :abbreviation => 'AZ', :ansi_code => '4', :statens => '1779777'},
  { :name => 'Arkansas', :abbreviation => 'AR', :ansi_code => '5', :statens => '68085'},
  { :name => 'California', :abbreviation => 'CA', :ansi_code => '6', :statens => '1779778'},
  { :name => 'Colorado', :abbreviation => 'CO', :ansi_code => '8', :statens => '1779779'},
  { :name => 'Connecticut', :abbreviation => 'CT', :ansi_code => '9', :statens => '1779780'},
  { :name => 'Delaware', :abbreviation => 'DE', :ansi_code => '10', :statens => '1779781'},
  { :name => 'District of Columbia', :abbreviation => 'DC', :ansi_code => '11', :statens => '1702382'},
  { :name => 'Florida', :abbreviation => 'FL', :ansi_code => '12', :statens => '294478'},
  { :name => 'Georgia', :abbreviation => 'GA', :ansi_code => '13', :statens => '1705317'},
  { :name => 'Hawaii', :abbreviation => 'HI', :ansi_code => '15', :statens => '1779782'},
  { :name => 'Idaho', :abbreviation => 'ID', :ansi_code => '16', :statens => '1779783'},
  { :name => 'Illinois', :abbreviation => 'IL', :ansi_code => '17', :statens => '1779784'},
  { :name => 'Indiana', :abbreviation => 'IN', :ansi_code => '18', :statens => '448508'},
  { :name => 'Iowa', :abbreviation => 'IA', :ansi_code => '19', :statens => '1779785'},
  { :name => 'Kansas', :abbreviation => 'KS', :ansi_code => '20', :statens => '481813'},
  { :name => 'Kentucky', :abbreviation => 'KY', :ansi_code => '21', :statens => '1779786'},
  { :name => 'Louisiana', :abbreviation => 'LA', :ansi_code => '22', :statens => '1629543'},
  { :name => 'Maine', :abbreviation => 'ME', :ansi_code => '23', :statens => '1779787'},
  { :name => 'Maryland', :abbreviation => 'MD', :ansi_code => '24', :statens => '1714934'},
  { :name => 'Massachusetts', :abbreviation => 'MA', :ansi_code => '25', :statens => '606926'},
  { :name => 'Michigan', :abbreviation => 'MI', :ansi_code => '26', :statens => '1779789'},
  { :name => 'Minnesota', :abbreviation => 'MN', :ansi_code => '27', :statens => '662849'},
  { :name => 'Mississippi', :abbreviation => 'MS', :ansi_code => '28', :statens => '1779790'},
  { :name => 'Missouri', :abbreviation => 'MO', :ansi_code => '29', :statens => '1779791'},
  { :name => 'Montana', :abbreviation => 'MT', :ansi_code => '30', :statens => '767982'},
  { :name => 'Nebraska', :abbreviation => 'NE', :ansi_code => '31', :statens => '1779792'},
  { :name => 'Nevada', :abbreviation => 'NV', :ansi_code => '32', :statens => '1779793'},
  { :name => 'New Hampshire', :abbreviation => 'NH', :ansi_code => '33', :statens => '1779794'},
  { :name => 'New Jersey', :abbreviation => 'NJ', :ansi_code => '34', :statens => '1779795'},
  { :name => 'New Mexico', :abbreviation => 'NM', :ansi_code => '35', :statens => '897535'},
  { :name => 'New York', :abbreviation => 'NY', :ansi_code => '36', :statens => '1779796'},
  { :name => 'North Carolina', :abbreviation => 'NC', :ansi_code => '37', :statens => '1027616'},
  { :name => 'North Dakota', :abbreviation => 'ND', :ansi_code => '38', :statens => '1779797'},
  { :name => 'Ohio', :abbreviation => 'OH', :ansi_code => '39', :statens => '1085497'},
  { :name => 'Oklahoma', :abbreviation => 'OK', :ansi_code => '40', :statens => '1102857'},
  { :name => 'Oregon', :abbreviation => 'OR', :ansi_code => '41', :statens => '1155107'},
  { :name => 'Pennsylvania', :abbreviation => 'PA', :ansi_code => '42', :statens => '1779798'},
  { :name => 'Rhode Island', :abbreviation => 'RI', :ansi_code => '44', :statens => '1219835'},
  { :name => 'South Carolina', :abbreviation => 'SC', :ansi_code => '45', :statens => '1779799'},
  { :name => 'South Dakota', :abbreviation => 'SD', :ansi_code => '46', :statens => '1785534'},
  { :name => 'Tennessee', :abbreviation => 'TN', :ansi_code => '47', :statens => '1325873'},
  { :name => 'Texas', :abbreviation => 'TX', :ansi_code => '48', :statens => '1779801'},
  { :name => 'Utah', :abbreviation => 'UT', :ansi_code => '49', :statens => '1455989'},
  { :name => 'Vermont', :abbreviation => 'VT', :ansi_code => '50', :statens => '1779802'},
  { :name => 'Virginia', :abbreviation => 'VA', :ansi_code => '51', :statens => '1779803'},
  { :name => 'Washington', :abbreviation => 'WA', :ansi_code => '53', :statens => '1779804'},
  { :name => 'West Virginia', :abbreviation => 'WV', :ansi_code => '54', :statens => '1779805'},
  { :name => 'Wisconsin', :abbreviation => 'WI', :ansi_code => '55', :statens => '1779806'},
  { :name => 'Wyoming', :abbreviation => 'WY', :ansi_code => '56', :statens => '1779807'}
])

